# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Glovo' do
  use_frameworks!
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Swinject', '~> 2.4.0'
  pod 'PKHUD', '~> 5.0'
  pod 'ReactiveKit'
  pod 'Bond'
end
